const router = require('express').Router();
const authMid = require('../../middlewares/auth.middleware');
const authCon = require('../../controllers/auth.controller');
const passport = require('passport');
const passportConfig = require('../../config/passport');
passportConfig(passport);
router.get('/auth/google', passport.authenticate('google', { scope: ['profile', 'email'] }));
router.get('/auth/google/callback', passport.authenticate('google', { failureRedirect: '/login' }), function (req, res) {
    res.redirect('/');
});
router.get('/facebook/callback', authCon.handleLoginFacebook);
router.get('/facebook', passport.authenticate('facebook', { scope: ['email', 'public_profile'] }));
router.post('/complete', authCon.hanleCompleteUser);
router.get('/otp/:userId', authCon.sendOTP);
router.post('/signin', authMid.isNotSignedIn, authCon.handleSignIn);
router.post('/signup', authMid.isNotSignedIn, authMid.isValidEmail, authCon.handleSignUp);
router.post('/forget', authCon.forget);
router.put('/reset/:id', authMid.authenticate, authCon.reset);
router.put('/active/:id', authCon.activeAccount);
router.delete('/signout', authMid.authenticate, authCon.handleSignOut);
module.exports = router;
