const router = require('express').Router();
const authMid = require('../../middlewares/auth.middleware');
const authCon = require('../../controllers/auth.controller');
const passport = require('passport');
const passportConfig = require('../../config/passport');
passportConfig(passport);
router.post('/facebook', authCon.handleLoginByFacebook);
router.post('/google', authCon.handleLoginByGoogle);
router.route('/complete').post(authCon.handleComplete).put(authCon.handleComplete);
router.get('/otp/:userId', authCon.sendOTP);
router.post('/signin', authMid.isNotSignedIn, authCon.handleSignIn);
router.post('/signup', authMid.isNotSignedIn, authMid.isValidEmail, authCon.handleSignUp);
router.post('/forget', authCon.forget);
router.put('/reset/:id', authMid.authenticate, authCon.reset);
router.put('/active/:id', authCon.activeAccount);
router.delete('/signout', authMid.authenticate, authCon.handleSignOut);
module.exports = router;
